---
language: python
python: "2.7"
services:
- docker

env:
  matrix:
  - ANSIBLE_VERSION=1.9.4 ANSIBLE_ROLE=common
  - ANSIBLE_VERSION=1.9.4 ANSIBLE_ROLE=ruby
  - ANSIBLE_VERSION=2.1.2 ANSIBLE_ROLE=common
  - ANSIBLE_VERSION=2.1.2 ANSIBLE_ROLE=ruby

before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq python-apt python-pycurl

install:
  - pip install ansible=="$ANSIBLE_VERSION"

script:
  - echo localhost > inventory
  - ansible-playbook -i inventory tests/$ANSIBLE_ROLE.yml --syntax-check
  - ansible-playbook -i inventory tests/$ANSIBLE_ROLE.yml --connection=local --sudo
  - >
    ansible-playbook -i inventory tests/$ANSIBLE_ROLE.yml --connection=local --sudo
    | grep -q '.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)
