---
- name: Create swap file
  command: dd if=/dev/zero of={{ swap_file_path }} bs=128M count={{ ((swap_size_mb-1)/128)|int+1 }}
           creates="{{ swap_file_path }}"

- name: Change swap file permissions
  file: path="{{ swap_file_path }}"
        owner=root
        group=root
        mode=0600

- name: "Check swap file type"
  command: file {{ swap_file_path }}
  register: swapfile

- name: Make swap file
  command: "sudo mkswap {{ swap_file_path }}"
  register: write_swapfile
  when: swapfile.stdout.find('swap file') == -1

- name: Write swap entry in fstab
  mount: name=none
         src={{ swap_file_path }}
         fstype=swap
         opts=sw
         passno=0
         dump=0
         state=present

- name: Mount swap
  command: "swapon {{ swap_file_path }}"
  when: swap_size_mb > 1 and write_swapfile.changed
