---
- include: install-packages.yml
  become_user: root
  tags:
    - security

- include: add-sudoer.yml
  become_user: root
  tags:
    - security

- include: configure-ssh.yml
  become_user: root
  tags:
    - security

- include: configure-ufw.yml
  become_user: root
  tags:
    - security
