---
- include: configure-locale.yml
  become_user: root
  tags:
    - common

- include: install-packages.yml
  become_user: root
  tags:
    - common

- include: add-deploy-user.yml
  become_user: root
  tags:
    - common

- include: configure-bash.yml
  become_user: "{{ deploy_user }}"
  tags:
    - common

