---
- name: Installs rbenv
  git: repo=git://github.com/sstephenson/rbenv.git dest=~{{ deploy_user }}/.rbenv accept_hostkey=yes

- name: Ensure .bash.d dir exists
  file: dest=~{{ deploy_user }}/.bash.d/ state=directory

- name: Installs rbenv bash file
  copy: src=50_rbenv.bash dest=~{{ deploy_user }}/.bash.d/50_rbenv.bash mode=700 owner={{ deploy_user }}

- name: Source rbenv bash file in .bash_stuff
  lineinfile: dest=~{{ deploy_user }}/.bash_stuff regexp="rbenv" insertafter=EOF line="source ~/.bash.d/50_rbenv.bash" create=yes

- name: Creates plugin directory
  file: path=~{{ deploy_user }}/.rbenv/plugins/ owner={{ deploy_user }} group={{ deploy_user }} mode=0755 state=directory

- name: Installs ruby-build
  git: repo=git://github.com/sstephenson/ruby-build.git dest=~{{ deploy_user }}/.rbenv/plugins/ruby-build

- name: Installs rbenv-vars
  git: repo=git://github.com/sstephenson/rbenv-vars.git dest=~{{ deploy_user }}/.rbenv/plugins/rbenv-vars

- name: Adds .gemrc
  copy: src=gemrc dest=~{{ deploy_user }}/.gemrc owner={{ deploy_user }} group={{ deploy_user }} mode=0750

