---
- include: install-rbenv.yml
  sudo: yes
  sudo_user: "{{ deploy_user }}"
  tags:
    - ruby

- include: install-ruby.yml
  sudo: yes
  sudo_user: "{{ deploy_user }}"
  tags:
    - ruby

- include: install-ruby-gems.yml
  sudo: yes
  sudo_user: "{{ deploy_user }}"
  tags:
    - ruby
