---
- include: install-rbenv.yml
  become_user: "{{ deploy_user }}"
  tags:
    - ruby

- include: install-ruby.yml
  become_user: "{{ deploy_user }}"
  tags:
    - ruby

- include: install-ruby-gems.yml
  become_user: "{{ deploy_user }}"
  tags:
    - ruby
